// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCalculator.DataAccess.Data;

#nullable disable

namespace SimpleCalculator.DataAccessLibrary.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    [Migration("20221206231044_AddMathOperatorColumn")]
    partial class AddMathOperatorColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCalculator.DataAccessLibrary.Model.CalculatorMemory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FirstNumber")
                        .HasColumnType("float");

                    b.Property<string>("MathOperator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Result")
                        .HasColumnType("float");

                    b.Property<double>("SecondNumber")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CalculatorMemories");
                });
#pragma warning restore 612, 618
        }
    }
}
